### ISSUE TITLE
A loading error in Win System.

### ISSUE THREAD

**Issue by igo312** [faroit/stempeg#30]
my data has a name format like 'xxxx - xxxx.stem.m64'. but `stempeg` cannot reconginize the blank space before "-". So it will raise a error said there is no file.

The dataset actually is [MUSDB18-7](https://zenodo.org/record/3270814) set

I solve it by following codes which actually deletes the front blank space. But I hope there is a better way to solve it.

```python
index = track_name.index('-')
track_name = track_name[:index-1] + track_name[index:]
```

**Comment by faroit** [comment]
Thanks for the report. Can you tell me which line triggers the error?

**Comment by igo312** [comment]
here's my tranceback. It is may not `stempeg`'s  fault, but I only trace it to this module.

```python 
Traceback (most recent call last):
  File "C:/Users/acer/Desktop/LVA-ICA-2018-master/LVA-ICA-2018-master/RGT1/analyze.py", line 17, in <module>
    mus = musdb.DB(root="F:\\MUSDB18-7")
  File "F:\python36\lib\site-packages\musdb\__init__.py", line 110, in __init__
    self.tracks = self.load_mus_tracks(subsets=subsets, split=split)
  File "F:\python36\lib\site-packages\musdb\__init__.py", line 255, in load_mus_tracks
    is_wav=self.is_wav,
  File "F:\python36\lib\site-packages\musdb\audio_classes.py", line 141, in __init__
    super(MultiTrack, self).__init__(path=path, *args, **kwargs)
  File "F:\python36\lib\site-packages\musdb\audio_classes.py", line 53, in __init__
    self.info = stempeg.Info(self.path)
  File "F:\python36\lib\site-packages\stempeg\read.py", line 38, in __init__
    self.json_info = read_info(self.filename)
  File "F:\python36\lib\site-packages\stempeg\read.py", line 93, in read_info
    out = sp.check_output(cmd)
  File "F:\python36\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "F:\python36\lib\subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "F:\python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "F:\python36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

```

**Comment by igo312** [comment]
Update:
sorry for my poor thought about the problem. Right now, I don't think it's a name format problem. I delete all blank space and use `os.path.exits()` to check whether the file exists. 
And I get `True` from `os.path.exits()`. but same error infos from `stempeg.Info()`
```python
>>>os.path.exists(r'F:\MUSDB18-7\AlJames-SchoolboyFacination.stem.mp4')
True

>>>stempeg.Info(r'F:\MUSDB18-7\AlJames-SchoolboyFacination.stem.mp4')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "F:\python36\lib\site-packages\stempeg\read.py", line 38, in __init__
    self.json_info = read_info(self.filename)
  File "F:\python36\lib\site-packages\stempeg\read.py", line 93, in read_info
    out = sp.check_output(cmd)
  File "F:\python36\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "F:\python36\lib\subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "F:\python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "F:\python36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

**Comment by faroit** [comment]
Ok. Can you check if you have ffprobe installed?

**Comment by igo312** [comment]
Well，it seems work by downloading  [ffmpeg.zip](http://ffmpeg.org/download.html#build-windows) add them to `env_path`. Thank you @faroit !

**Attention** `pip install ffprobe` cannot solve problem

**Comment by faroit** [comment]
Great, that it works

> Attention pip install ffprobe cannot solve problem

this is part of the ffmpeg installation. It cannot be installed with pip as pip only installs python software
